name: cpp-aecmio
version: master
summary: blockchain app platform
description: aecmio C++ project

grade: devel
confinement: devmode

apps:
  aec:
    command: aec
  aecvm:
    command: aecvm

parts:
  cpp-aecmio:
    source: .
    source-type: git
    plugin: cmake
    build-packages:
      - build-essential
      - libgmp-dev
      - libleveldb-dev
